FROM bellsoft/liberica-openjdk-alpine:11.0.11

COPY ./java ./src 
RUN mkdir ./out
RUN javac -sourcepath ./src -d out src/ru/geekbrains/lesson1/app/App.java

CMD java -classpath ./out ru.geekbrains.lesson1.app.App
